#! /bin/bash

export VERSION="45"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="10000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	adobe-source-han-sans-cn-fonts \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	broadcom-wl-dkms \
	cifs-utils \
	diffutils \
	dconf-editor \
	dkms \
	distrobox \
	dmidecode \
	dosbox \
	eog \
	epiphany \
	ethtool \
	evtest \
	efibootmgr \
	expect \
	exfatprogs \
	ffmpeg \
	file-roller \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	f2fs-tools \
	gamemode \
	git \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-text-editor \
	gnome-icon-theme-extras \
	gnome-tweaks \
	gnome-shell-extensions \
	gnome-menus \
	gst-plugin-pipewire \
	gparted \
	haveged \
	htop \
	ibus-pinyin \
	ibus-table-chinese \
	ibus-anthy \
	ibus-hangul \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	jq \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-gamemode \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-vdpau-driver \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libretro-beetle-pce-fast \
	libretro-beetle-psx-hw \
	libretro-citra \
	libretro-desmume \
	libretro-dolphin \
	libretro-flycast \
	libretro-genesis-plus-gx \
	libretro-kronos \
	libretro-mesen-s\
	libretro-mgba \
	libretro-mupen64plus-next \
	libretro-nestopia \
	libretro-picodrive \
	libretro-ppsspp \
	libretro-shaders-slang \
	libretro-snes9x \
	libva-intel-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	liquidctl \
	logrotate \
	lshw \
	mesa-demos \
	modemmanager \
	nano \
	nautilus \
	networkmanager \
	nfs-utils \
	noto-fonts-emoji \
	nss-mdns \
	ntfs-3g \
	openal \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	papirus-icon-theme \
	retroarch \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	s-tui \
	tree \
	ttf-liberation \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	v2ray \
	wavpack \
	wget \
	which \
	wireplumber \
	wine \
	xdg-desktop-portal \
	xdg-desktop-portal-gnome \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	zram-generator \
	zsh \
"

export PACKAGE_OVERRIDES="\
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.6.0.rc5-chos1-1/linux-chimeraos-6.6.0.rc5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.6.0.rc5-chos1-1/linux-chimeraos-headers-6.6.0.rc5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/lib32-libva-mesa-driver-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/lib32-mesa-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/lib32-mesa-vdpau-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/lib32-vulkan-intel-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/lib32-vulkan-radeon-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/libva-mesa-driver-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/mesa-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/mesa-vdpau-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/vulkan-intel-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.2.1-chos1-2/vulkan-radeon-23.2.1.chos1-2-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/repos/2023/06/28/extra/os/x86_64/libretro-pcsx2-11900-2-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/l/libretro-mame/libretro-mame-85763-1-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	anydesk-bin \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	boxtron \
	chimera \
	downgrade \
	frzr-sk \
	gamescope-plus \
	gamescope-session-git \
	gnome-shell-extension-clipboard-indicator \
	gnome-shell-extension-desktop-icons-ng \
	hhfc-git \
	legendary \
	lib32-gamescope-plus \
	lib32-gperftools \
	libretro-dosbox-pure-git \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	kanit-font \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	onedrive-abraunegg \
	pikaur \
	python-vdf \
	protonup-qt-bin \
	protontricks \
	r8152-dkms \
	r8168-dkms \
	retroarch-autoconfig-udev-git \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl88x2bu-dkms-git \
	rtl8821au-dkms-git \
	rtw89-dkms-git \
	ryzenadj-git \
	rz608-fix-git \
	steam-removable-media-git \
	sk-chos-tool \
	sk-boot-to-windows \
	v2raya-bin \
	wyvern \
	yay-bin \
	xpad-noone-dkms \
	zenergy-dkms-git \
"

export PACKAGES_TO_DELETE="\
	jack2 \
	pulseaudio \
	pulseaudio-alsa \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	auto-expand-home \
	fstrim.timer \
	frzr_root-swap-swapfile.swap \
	handycon \
	haveged \
	lightdm \
	sshd \
	systemd-timesyncd \
	swapfile \
	sk-auto-keep-boot-entry \
	sk-update-boot-entry \
	sk-resume \
"

export USER_SERVICES="\
	chimera.service \
	clear-gamescope-modes \
	gamemoded.service \
	ryzen-tctl \
	steam-patch.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/libretro/autoconfig/udev/Gasia_PS_Gamepad_USB.cfg \
	/usr/share/libretro/autoconfig/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg \
	/usr/share/libretro/autoconfig/udev/Xbox_360_Wireless_Receiver_Chinese01.cfg \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" > /etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" > /etc/sudoers.d/chimera
	echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/${USERNAME}"

	sed -i 's/set mouse=a/set mouse-=a/g' /usr/share/vim/vim90/defaults.vim
	ln -s -f /usr/bin/vim /usr/bin/vi

	sed -i "s#/home/${USERNAME}:/bin/bash#/home/${USERNAME}:/bin/zsh#" /etc/passwd
	sed -i "s#/root:/bin/bash#/root:/bin/zsh#" /etc/passwd
	
	sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config

	sed -i "s/# export STEAM_GAMESCOPE_COLOR_MANAGED=1/export STEAM_GAMESCOPE_COLOR_MANAGED=1/" /usr/share/gamescope-session/gamescope-session-script

	# disable retroarch menu in joypad configs
	find /usr/share/libretro/autoconfig -type f -name '*.cfg' | xargs -d '\n' sed -i '/input_menu_toggle_btn/d'

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
	find /usr/share/applications/* | \
	grep -v anydesk.desktop | \
	grep -v ca.desrt.dconf-editor.desktop | \
	grep -v gparted.desktop | \
	grep -v org.chimeraos.Gamescope.desktop | \
	grep -v org.chimeraos.app.desktop | \
	grep -v org.gnome.Console.desktop | \
	grep -v org.gnome.DiskUtility.desktop | \
	grep -v org.gnome.FileRoller.desktop | \
	grep -v org.gnome.Nautilus.desktop | \
	grep -v org.gnome.Settings.desktop | \
	grep -v org.gnome.Software.desktop | \
	grep -v org.gnome.TextEditor.desktop | \
	grep -v org.gnome.tweaks.desktop | \
	grep -v org.gnome.Extensions.desktop | \
	grep -v protonup-qt.desktop | \
	grep -v protontricks.desktop | \
	grep -v steam.desktop | \
	grep -v sk-chos-tool.desktop | \
	grep -v sk-chos-tool-command.desktop | \
	grep -v com.github.tchx84.Flatseal.desktop | \
	xargs -I {} sh -c "echo NoDisplay=true >> {}"

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

	# set permissions for intel_gpu_top and mangohud
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
}

